# Generated by Django 5.1.1 on 2024-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_case', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_condition', models.TextField(blank=True, null=True)),
                ('test_steps', models.TextField(blank=True, null=True)),
                ('test_data', models.TextField(blank=True, null=True)),
                ('expected_result', models.TextField(blank=True, null=True)),
                ('actual_result', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_fail', models.CharField(blank=True, max_length=10, null=True)),
                ('bug_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
